"""Add source registry operational fields

Revision ID: a326f99b4d95
Revises: 20260501_0002
Create Date: 2026-04-30 18:27:59.046477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a326f99b4d95'
down_revision: Union[str, Sequence[str], None] = '20260501_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_correctness_checks', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('boundaries', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('boundaries', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('case_parties', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('case_parties', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('cases', 'case_type',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('cases', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('cases', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('courtlistener_bulk_runs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_cl_bulk_runs_snapshot_date'), table_name='courtlistener_bulk_runs')
    op.drop_index(op.f('ix_cl_bulk_runs_status'), table_name='courtlistener_bulk_runs')
    op.create_index(op.f('ix_courtlistener_bulk_runs_snapshot_date'), 'courtlistener_bulk_runs', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_courtlistener_bulk_runs_status'), 'courtlistener_bulk_runs', ['status'], unique=False)
    op.alter_column('courts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('courts', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('crime_incidents', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('crime_incidents', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('defendants', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('defendants', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_esr_canonical_entity_id'), table_name='entity_source_records')
    op.drop_index(op.f('ix_esr_source_name'), table_name='entity_source_records')
    op.drop_index(op.f('ix_esr_source_record'), table_name='entity_source_records')
    op.drop_index(op.f('ix_esr_unique_source_record'), table_name='entity_source_records')
    op.create_index(op.f('ix_entity_source_records_canonical_entity_id'), 'entity_source_records', ['canonical_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_source_records_source_name'), 'entity_source_records', ['source_name'], unique=False)
    op.alter_column('events', 'source_quality',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('events', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('events', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('ingestion_runs', 'status',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('ingestion_runs', 'fetched_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ingestion_runs', 'parsed_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ingestion_runs', 'persisted_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ingestion_runs', 'skipped_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ingestion_runs', 'error_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ingestion_runs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('ingestion_runs', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('judges', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('judges', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('legal_sources', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('legal_sources', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('locations', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('locations', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('outcomes', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('outcomes', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_rel_evidence_evidence_source'), table_name='relationship_evidence')
    op.drop_index(op.f('ix_rel_evidence_from_entity_id'), table_name='relationship_evidence')
    op.drop_index(op.f('ix_rel_evidence_from_entity_type'), table_name='relationship_evidence')
    op.drop_index(op.f('ix_rel_evidence_relationship_type'), table_name='relationship_evidence')
    op.drop_index(op.f('ix_rel_evidence_snapshot_id'), table_name='relationship_evidence')
    op.drop_index(op.f('ix_rel_evidence_to_entity_id'), table_name='relationship_evidence')
    op.drop_index(op.f('ix_rel_evidence_to_entity_type'), table_name='relationship_evidence')
    op.create_index(op.f('ix_relationship_evidence_evidence_snapshot_id'), 'relationship_evidence', ['evidence_snapshot_id'], unique=False)
    op.create_index(op.f('ix_relationship_evidence_evidence_source'), 'relationship_evidence', ['evidence_source'], unique=False)
    op.create_index(op.f('ix_relationship_evidence_from_entity_id'), 'relationship_evidence', ['from_entity_id'], unique=False)
    op.create_index(op.f('ix_relationship_evidence_from_entity_type'), 'relationship_evidence', ['from_entity_type'], unique=False)
    op.create_index(op.f('ix_relationship_evidence_relationship_type'), 'relationship_evidence', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_relationship_evidence_to_entity_id'), 'relationship_evidence', ['to_entity_id'], unique=False)
    op.create_index(op.f('ix_relationship_evidence_to_entity_type'), 'relationship_evidence', ['to_entity_type'], unique=False)
    op.alter_column('review_action_logs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('review_items', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.add_column('source_registry', sa.Column('rate_limit_rpm', sa.Integer(), nullable=True))
    op.add_column('source_registry', sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('source_registry', sa.Column('health_score', sa.Float(), nullable=False))
    op.add_column('source_registry', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_source_registry_country'), table_name='source_registry')
    op.drop_index(op.f('ix_source_registry_is_active'), table_name='source_registry')
    op.drop_index(op.f('ix_source_registry_source_key'), table_name='source_registry')
    op.drop_index(op.f('ix_source_registry_source_type'), table_name='source_registry')
    op.drop_index(op.f('ix_source_snapshots_content_hash'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_fetched_at'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_source_url'), table_name='source_snapshots')
    op.alter_column('topics', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('topics', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topics', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('topics', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_source_snapshots_source_url'), 'source_snapshots', ['source_url'], unique=False)
    op.create_index(op.f('ix_source_snapshots_fetched_at'), 'source_snapshots', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_source_snapshots_content_hash'), 'source_snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_registry_source_type'), 'source_registry', ['source_type'], unique=False)
    op.create_index(op.f('ix_source_registry_source_key'), 'source_registry', ['source_key'], unique=False)
    op.create_index(op.f('ix_source_registry_is_active'), 'source_registry', ['is_active'], unique=False)
    op.create_index(op.f('ix_source_registry_country'), 'source_registry', ['country'], unique=False)
    op.drop_column('source_registry', 'admin_notes')
    op.drop_column('source_registry', 'health_score')
    op.drop_column('source_registry', 'last_ingested_at')
    op.drop_column('source_registry', 'rate_limit_rpm')
    op.alter_column('review_items', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('review_action_logs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_relationship_evidence_to_entity_type'), table_name='relationship_evidence')
    op.drop_index(op.f('ix_relationship_evidence_to_entity_id'), table_name='relationship_evidence')
    op.drop_index(op.f('ix_relationship_evidence_relationship_type'), table_name='relationship_evidence')
    op.drop_index(op.f('ix_relationship_evidence_from_entity_type'), table_name='relationship_evidence')
    op.drop_index(op.f('ix_relationship_evidence_from_entity_id'), table_name='relationship_evidence')
    op.drop_index(op.f('ix_relationship_evidence_evidence_source'), table_name='relationship_evidence')
    op.drop_index(op.f('ix_relationship_evidence_evidence_snapshot_id'), table_name='relationship_evidence')
    op.create_index(op.f('ix_rel_evidence_to_entity_type'), 'relationship_evidence', ['to_entity_type'], unique=False)
    op.create_index(op.f('ix_rel_evidence_to_entity_id'), 'relationship_evidence', ['to_entity_id'], unique=False)
    op.create_index(op.f('ix_rel_evidence_snapshot_id'), 'relationship_evidence', ['evidence_snapshot_id'], unique=False)
    op.create_index(op.f('ix_rel_evidence_relationship_type'), 'relationship_evidence', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_rel_evidence_from_entity_type'), 'relationship_evidence', ['from_entity_type'], unique=False)
    op.create_index(op.f('ix_rel_evidence_from_entity_id'), 'relationship_evidence', ['from_entity_id'], unique=False)
    op.create_index(op.f('ix_rel_evidence_evidence_source'), 'relationship_evidence', ['evidence_source'], unique=False)
    op.alter_column('outcomes', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('outcomes', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('locations', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('locations', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('legal_sources', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('legal_sources', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('judges', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('judges', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('ingestion_runs', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('ingestion_runs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('ingestion_runs', 'error_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ingestion_runs', 'skipped_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ingestion_runs', 'persisted_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ingestion_runs', 'parsed_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ingestion_runs', 'fetched_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ingestion_runs', 'status',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('events', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('events', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('events', 'source_quality',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_index(op.f('ix_entity_source_records_source_name'), table_name='entity_source_records')
    op.drop_index(op.f('ix_entity_source_records_canonical_entity_id'), table_name='entity_source_records')
    op.create_index(op.f('ix_esr_unique_source_record'), 'entity_source_records', ['source_table', 'source_record_id', 'source_name'], unique=1)
    op.create_index(op.f('ix_esr_source_record'), 'entity_source_records', ['source_table', 'source_record_id'], unique=False)
    op.create_index(op.f('ix_esr_source_name'), 'entity_source_records', ['source_name'], unique=False)
    op.create_index(op.f('ix_esr_canonical_entity_id'), 'entity_source_records', ['canonical_entity_id'], unique=False)
    op.alter_column('defendants', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('defendants', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('crime_incidents', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('crime_incidents', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('courts', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('courts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_courtlistener_bulk_runs_status'), table_name='courtlistener_bulk_runs')
    op.drop_index(op.f('ix_courtlistener_bulk_runs_snapshot_date'), table_name='courtlistener_bulk_runs')
    op.create_index(op.f('ix_cl_bulk_runs_status'), 'courtlistener_bulk_runs', ['status'], unique=False)
    op.create_index(op.f('ix_cl_bulk_runs_snapshot_date'), 'courtlistener_bulk_runs', ['snapshot_date'], unique=False)
    op.alter_column('courtlistener_bulk_runs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('cases', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('cases', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('cases', 'case_type',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('case_parties', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('case_parties', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('boundaries', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('boundaries', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('ai_correctness_checks', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###
